// suppress inspection "SpellCheckingInspection" for whole file
// suppress inspection "GrazieInspection" for whole file
= RssNaiveApi project
:toc:
:hardbreaks:

This API is intended to be used as a Java component.
Several ways to tests it :

* REST API
* JUnit unit tests
* Naive Main

See below.

== Development

The entire code has been developed under IDEA IntelliJ 2020.3 with some additionnal plugins :

* Lombok
* Junit

== Build and unit test

Just type text hereafter after git clone :

 mvn clean verify

successfully built w/ :

* Maven 3.6.3
* OpenJDK version 11.0.10
* on Ubuntu 21.04.

succesfully unit tests w/ :

* JUnit 5

== Packaging

All elements are packaged as a Jar archive, including SpringBoot application.

Source and javadoc Jars are also provided to help developer to use the API.

== Java API

=== Features

It exposes two methods.

==== getTitlesAndUrls

Designed to answer this user story :

_As a user, I want to search and consult RSS feeds from several sources, for example :
- https://www.wired.com/feed/category/science/latest/rss
- https://www.techrepublic.com/rssfeeds/articles/
- ..._

This method returns a Collection of titles and URL.
The developer can show them in a UI for User interaction.

==== addFeed

Designed to answer this user story :

_As an admin, I can add and configure new RSS feeds into the system.
The configuration must include :
- The feed URL - The periodicity (how often the feed is refreshed) : each minute, each hour, each 12 hours, each day etc._

This method permits to add a Feed source and the period after which it will be refreshed.

=== Maven artifact GAV

.to import set in your POM :
....
    <groupId>org.fdu.application</groupId>
    <artifactId>RssNaiveApi</artifactId>
    <version>1.0.0</version>
....

WARNING: The RssNaiveApi artifact must have been deployed in a repository (example : Nexus) before using it in a POM.

== How to manual test the API ?

=== (preferred) via SpringBoot REST service application

==== Run application

.Run it with Maven
 $ mvn spring-boot:run

.Or run it with Java CLI
 $ java -jar target/RssNaiveApi-1.0.jar org.fdu.application.RssNaiveApplication

==== Test the Springboot REST Service

===== add feeds

.Use curl to test the REST API
....
curl \
    --header "Content-type: application/json" \
    --request POST \
    --data '{"urlStr":"source feed url","refreshDurationStr":"timeToRefresh"}' \
    http://localhost:8080/addfeed
....

.examples
....
$ curl --header "Content-type: application/json" \
    --request POST \
    --data '{"urlStr":"https://www.wired.com/feed/category/science/latest/rss","refreshDurationStr":"PT15M"}' \
    http://localhost:8080/addfeed
Added Science Latest

$ curl --header "Content-type: application/json" \
    --request POST \
    --data '{"urlStr":"https://www.techrepublic.com/rssfeeds/articles/","refreshDurationStr":"PT15M"}' \
    http://localhost:8080/addfeed
Added Articles on TechRepublic
....

IMPORTANT: To create a Duration object based on a text sequence, this has to be of the form “PnDTnHnMn.nS”:
cf https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-

Alternative :  Use postman or other tool to test (files NOT included in repo)

===== get feeds

.use curl
 curl -s --header "Content-type: application/json" --request GET http://localhost:8080/getfeeds |jq

.example
....
$ curl -s --header "Content-type: application/json" --request GET http://localhost:8080/getfeeds |jq
[
  {
    "entryTitle": "The Raging Evolutionary War Between Humans and Covid-19",
    "entryDesc": "Fighting the pandemic isn’t only about vaccines and drugs. It’s about understanding how viruses mutate and change inside us, and among us.",
    "entryUrl": "https://www.wired.com/story/the-raging-evolutionary-war-between-humans-and-covid-19"
  },
  {
...
....

IMPORTANT: don't forget to pipe with 'jq' to make the output human readable.

=== Via unit Tests

Use JUnit5 tests in :

* any IDE.
* via CLI

 mvn tests

Tested in : IntelliJ 2020.3

=== Via naive Main for NaiveRssApi

Launch

 src/main/java/org/fdu/application/RssNaiveImplMain.java

in any IDE.

Tested in : IntelliJ 2020.3

== How to automatically test the API ?

=== GitHub actions

GitHub Actions have been tested to automatize build/unit test actions.

=== Gitlab CI

With autodevops it has been tested on a experimental Gitlab repository.

== How to automatically run the REST API (doc only)

This part of the technical solution will only be documented.

. Add a Dockerfile to the repo in order to build the Docker image, SpringBoot Jar and  API in it.
. Push the created image in a image repository (dockerhub for instance)
. [optionnal] Add a compose file to either run a docker service or a docker stack depending of what kind of container you have (1 docker host or 1 docker swarm of many nodes)
. Instanciate your infra in any public cloud provider (AWS, GCP...)
. With Github actions (or any CI solution : Gitlab CI, Travis...), automatize the previous steps and the final docker run, compose-up or stack deploy

== Go further

* Use openAPI/swagger to design the API
* Travis CI
* Enhance/automate Springboot functionnal test
* Implement automatic run
